# Generated by Django 5.1.1 on 2024-10-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'BOTUSER', 'verbose_name_plural': 'BOTUSERS'},
        ),
    ]
